# Use custom format:
format="""
$hostname\
$directory\
$git_branch\
$direnv\
$aws\
$line_break\
$cmd_duration\
$character
"""

# TODO: add names for colors
palette = 'cli'
[palettes.cli]
#git_orange = "#f16148"

# Prompt symbols 
[character]
success_symbol = "[‚àÆ](#a6e3a1 bold)"
error_symbol = "[‚à≤](#f38ba8)"
vicmd_symbol = "[‚àÆ](#f9e2af)"

[directory]
format = "[ÓÇ∂]($style)[(bg:#89b4fa fg:#49628a)$path](bg:#89b4fa fg:#49628a)[ÓÇ¥ ]($style)"
style = "fg:#89b4fa"

[git_branch]
format = "[ÓÇ∂]($style)[[Óú• ](bg:#f16148 fg:#49628a bold)$branch](bg:#f16148 fg:#4c4f69)[ÓÇ¥ ]($style)"
style = "fg:#f16148"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[hostname]
ssh_only = true
format = "[ÓÇ∂]($style)[Û∞£Ä ](bg:bold dimmed white fg:#49628a bold)$hostname](bg:bold dimmed white fg:#4c4f69)[ÓÇ¥ ]($style)"
trim_at = "-"
style = "fg: bold dimmed white"
disabled = false

[aws]
format = "[ÓÇ∂]($style)[[‚òÅ ](bg:#f9e2af fg:#49628a bold) on $profile ($region) $duration](bg:#f9e2af fg:#4c4f69)[ÓÇ¥ ]($style)"
style = "fg:#f9e2af"

[python]
format = "[ÓÇ∂]($style)[[üêç ](bg:#f9e2af fg:#49628a bold) $version](bg:#f9e2af fg:#4c4f69)[ÓÇ¥ ]($style)"
style = "fg:#f9e2af"
